import { NextApiRequest, NextApiResponse } from 'next';
import Airtable from 'airtable';

const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY }).base(process.env.AIRTABLE_BASE_ID || '');

// ─── Static demo data returned for /report/demo ──────────────────────────
const DEMO_REPORT = {
    runId: 'demo',
    language: 'KO',
    rank1: {
        category: {
            category_id: 'FRAC_1550',
            category_display_name: 'Fractional 1550nm Laser',
            category_description: '피부 재생 레이저 치료로 피부 결을 개선하고 탄력을 높입니다.',
            avg_pain_level: '3/10',
            avg_downtime: '3-5일',
            recommended_sessions: '3-5회',
            session_interval_weeks: 4,
            budget_tier: 'Mid',
        },
        why_KO: '피부 텍스처 개선과 콜라겐 재생 효과가 검증된 프로토콜로, 다운타임 대비 효과가 우수합니다. 색소 병변에도 안전하게 적용 가능합니다.',
        why_EN: 'A clinically proven protocol for skin texture improvement and collagen regeneration with excellent results relative to downtime.',
        devices: [{ device_id: 'D_FRAXEL', device_name: 'Fraxel Dual 1550', primary_indication: '피부 재생', trend_score: 8 }],
        boosters: [{ booster_id: 'SB_REJURAN_HB', booster_name: 'Rejuran HB', canonical_role: 'regeneration', primary_effect: '피부 재생 및 탄력 개선' }]
    },
    rank2: {
        category: {
            category_id: 'MN_RF',
            category_display_name: 'RF 마이크로니들링',
            category_description: '고주파 에너지와 마이크로니들을 결합한 피부 타이트닝 치료입니다.',
            avg_pain_level: '4/10',
            avg_downtime: '1-2일',
            recommended_sessions: '3-4회',
            session_interval_weeks: 6,
            budget_tier: 'Mid',
        },
        why_KO: '진피층 콜라겐 재생을 직접 자극하며, 모공 축소와 피부 탄력 개선에 효과적입니다.',
        why_EN: 'Directly stimulates dermal collagen remodeling, effective for pore minimization and skin tightening.',
        devices: [{ device_id: 'D_GENIUS', device_name: 'Genius RF', primary_indication: '피부 탄력', trend_score: 9 }],
        boosters: [{ booster_id: 'SB_PRP', booster_name: 'PRP', canonical_role: 'regeneration', primary_effect: '성장인자를 통한 피부 재생' }]
    },
    rank3: {
        category: {
            category_id: 'IPL',
            category_display_name: 'IPL 토닝',
            category_description: '색소 병변과 홍조 개선에 효과적인 광치료입니다.',
            avg_pain_level: '2/10',
            avg_downtime: '없음',
            recommended_sessions: '5-6회',
            session_interval_weeks: 3,
            budget_tier: 'Low',
        },
        why_KO: '멜라닌 색소를 선택적으로 타겟하여 기미, 잡티 개선과 전반적인 피부톤 균일화에 효과적입니다.',
        why_EN: 'Selectively targets melanin pigmentation to improve melasma, age spots, and overall skin tone uniformity.',
        devices: [{ device_id: 'D_ICON', device_name: 'Icon IPL', primary_indication: '색소 개선', trend_score: 7 }],
        boosters: []
    },
    skinAnalysis: {
        ko: '이것은 샘플 데모 리포트입니다. 실제 피부 분석 결과는 설문 완료 후 AI가 개인 맞춤형으로 생성합니다. 피부 타입, 고민, 라이프스타일을 종합적으로 분석하여 최적의 시술을 추천드립니다.',
        en: 'This is a sample demo report. Your actual skin analysis will be personally generated by AI after completing the survey, taking into account your skin type, concerns, and lifestyle.'
    },
    whatToAvoid: { ko: '과도한 자외선 노출 및 열 자극이 강한 시술은 피부 상태를 악화시킬 수 있으므로 주의가 필요합니다.' },
    overallDirection: { ko: '피부 재생과 탄력 개선을 중심으로 단계적인 시술을 권장합니다.' },
    doctorQuestion: {
        ko: '1. 현재 피부 상태에 가장 적합한 시술 순서는 어떻게 되나요?\n2. 시술 간격은 얼마나 두는 것이 좋을까요?\n3. 색소 병변이 있는데 레이저 시술이 안전한가요?',
        en: '1. What is the recommended treatment sequence for my current skin condition?\n2. How long should I wait between sessions?\n3. Is laser treatment safe given my pigmentation history?'
    },
    surveyMeta: { name: '데모 고객' }
};

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

    const { id, lang } = req.query; // id is runId
    if (!id || typeof id !== 'string') return res.status(400).json({ error: 'Missing or invalid runId' });

    // ─── Handle demo page — return static data immediately ───────────────
    if (id === 'demo') {
        const demoLang = lang ? (lang as string).toUpperCase() : 'KO';
        return res.status(200).json({ ...DEMO_REPORT, language: demoLang });
    }

    try {
        // --- Step 1: Fetch Recommendation_Run record by runId ---
        let rrRec: any;
        try {
            rrRec = await base('Recommendation_Run').find(id);
        } catch (e: any) {
            if (e.statusCode === 404) {
                return res.status(200).json({ error: 'recommendation_not_ready' });
            }
            throw e;
        }

        const rrf = rrRec.fields || {};
        const status = rrf.status;
        const rank1CatId = (rrf.rank_1_category_id as string) || '';
        const rank2CatId = (rrf.rank_2_category_id as string) || '';
        const rank3CatId = (rrf.rank_3_category_id as string) || '';

        // --- Step 2: Check status ---
        if (status === 'error') {
            // Background function failed — stop polling, show error
            return res.status(200).json({ error: 'recommendation_failed' });
        }
        if (!rank1CatId && !rank2CatId && !rank3CatId) {
            // Still processing — keep polling
            return res.status(200).json({ error: 'recommendation_not_ready' });
        }

        // --- Step 3: Fetch EBD_Category for rank1/rank2/rank3 ---
        const categoryIdsToFetch = Array.from(new Set([rank1CatId, rank2CatId, rank3CatId].filter(Boolean)));
        let categoryRecords: any[] = [];

        if (categoryIdsToFetch.length > 0) {
            const catFormulas = categoryIdsToFetch.map(cId => `{category_id}="${cId}"`);
            const catResponse = await base('EBD_Category').select({
                filterByFormula: `OR(${catFormulas.join(',')})`,
                fields: [
                    'category_id', 'category_display_name', 'category_description',
                    'best_primary_indication', 'avg_pain_level', 'avg_downtime', 'recommended_sessions',
                    'session_interval_weeks', 'budget_tier', 'preferred_booster_roles',
                    'booster_pairing_note_KO', 'booster_pairing_note_EN',
                    'category_image', 'reason_why_EN', 'EBD_Device'
                ]
            }).all();
            categoryRecords = catResponse.map(r => ({ record_id: r.id, ...r.fields }));
        }

        // --- Step 4: Fetch EBD_Device ---
        const top10DevicesStr = (rrf.top10_device_ids as string) || '';
        const deviceIds = top10DevicesStr.split(',').map(s => s.trim()).filter(Boolean);
        let deviceRecords: any[] = [];

        if (deviceIds.length > 0) {
            const devFormulas = deviceIds.map(dId => `{device_id}="${dId}"`);
            const devResponse = await base('EBD_Device').select({
                filterByFormula: `OR(${devFormulas.join(',')})`,
                fields: [
                    'device_id', 'device_name', 'primary_indication', 'secondary_indication',
                    'avg_downtime_days', 'avg_pain_level', 'trend_score', 'brand_tier',
                    'clinical_evidence_score', 'signature_technology', 'clinical_charactor',
                    'reason_why', 'evidence_basis', 'launch_year'
                ]
            }).all();
            deviceRecords = devResponse.map(r => ({ record_id: r.id, ...r.fields }));
        }

        // --- Step 5: Fetch Skin_booster ---
        const top5BoostersStr = (rrf.top5_booster_ids as string) || '';
        const boosterIds = top5BoostersStr.split(',').map(s => s.trim()).filter(Boolean);
        let boosterRecords: any[] = [];

        if (boosterIds.length > 0) {
            const boosterFormulas = boosterIds.map(bId => `{booster_id}="${bId}"`);
            const boostResponse = await base('Skin_booster').select({
                filterByFormula: `OR(${boosterFormulas.join(',')})`,
                fields: [
                    'booster_id', 'booster_name', 'canonical_role', 'primary_effect', 'secondary_effect',
                    'target_layer', 'key_value', 'product_page_url'
                ]
            }).all();
            boosterRecords = boostResponse.map(r => ({ record_id: r.id, ...r.fields }));
        }

        // Helper to build rank output mapping devices and boosters
        const buildRank = (catId: string, whyKO: string, whyEN: string) => {
            if (!catId) return null;
            const category = categoryRecords.find(c => c.category_id === catId);
            if (!category) return null;

            // Link devices via the Airtable linked record IDs in category.EBD_Device
            const categoryDeviceRecordIds = (category.EBD_Device as string[]) || [];
            const rankDevices = deviceRecords.filter(d => categoryDeviceRecordIds.includes(d.record_id));

            // Link boosters by comparing category's preferred_booster_roles to booster's canonical_role
            const preferredRoles = (category.preferred_booster_roles as string || '').toLowerCase();
            const rankBoosters = boosterRecords.filter(b =>
                (b.canonical_role as string || '').toLowerCase().split(',').some(role => preferredRoles.includes(role.trim())) || preferredRoles.includes((b.canonical_role as string || '').toLowerCase())
            );

            // Clean internal tracking IDs
            const cleanObj = (obj: any) => { const { record_id, EBD_Device, ...rest } = obj; return rest; };

            return {
                category: cleanObj(category),
                why_KO: whyKO,
                why_EN: whyEN,
                devices: rankDevices.map(cleanObj),
                boosters: rankBoosters.map(cleanObj)
            };
        };

        const rank1 = buildRank(rank1CatId, rrf.why_cat1_KO as string, rrf.why_cat1_EN as string);
        const rank2 = buildRank(rank2CatId, rrf.why_cat2_KO as string, rrf.why_cat2_EN as string);
        const rank3 = buildRank(rank3CatId, rrf.why_cat3_KO as string, rrf.why_cat3_EN as string);

        let surveyMeta = {};
        try {
            if (rrf.survey_meta_json) {
                surveyMeta = JSON.parse(rrf.survey_meta_json as string);
            }
        } catch (e) {
            console.error('Failed to parse survey_meta_json', e);
        }

        // --- Step 6: Build final API response ---
        // Determine language: prefer URL ?lang param, then survey data, then default KO
        const detectedLang = req.query.lang
            ? (req.query.lang as string).toUpperCase()
            : ((surveyMeta as any)?.language || 'KO').toUpperCase();

        const apiResponse = {
            runId: id,
            language: detectedLang,
            rank1: rank1 || null,
            rank2: rank2 || null,
            rank3: rank3 || null,
            skinAnalysis: {
                ko: rrf.patient_summary as string || '',
                en: rrf.patient_friendly_summary as string || ''
            },
            whatToAvoid: {
                ko: rrf.clinical_warning as string || ''
            },
            overallDirection: {
                ko: rrf.comprehensive_analysis as string || ''
            },
            doctorQuestion: {
                ko: rrf.doctor_question_ko as string || '',
                en: rrf.doctor_question_en as string || ''
            },
            surveyMeta
        };

        return res.status(200).json(apiResponse);

    } catch (error: any) {
        console.error('[Report V3 API Error]', error);
        return res.status(500).json({ error: 'Internal Server Error' });
    }
}
