// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = "/" | "/admin/reports" | "/dashboard" | "/doctor-pending" | "/doctor/onboarding" | "/doctor/patient/[id]" | "/doctor/waitlist" | "/feedback" | "/login" | "/privacy" | "/report-v2/[id]" | "/report/[id]" | "/signup" | "/survey-v2" | "/terms"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/reports": {}
  "/dashboard": {}
  "/doctor-pending": {}
  "/doctor/onboarding": {}
  "/doctor/patient/[id]": { "id": string; }
  "/doctor/waitlist": {}
  "/feedback": {}
  "/login": {}
  "/privacy": {}
  "/report-v2/[id]": { "id": string; }
  "/report/[id]": { "id": string; }
  "/signup": {}
  "/survey-v2": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
