var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/pages/report/[id].js")
R.c("server/chunks/ssr/[root-of-the-server]__3aee9b97._.js")
R.c("server/chunks/ssr/_c17a840f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84687bd7._.js")
R.c("server/chunks/ssr/_79878c71._.js")
R.c("server/chunks/ssr/[externals]__dd7cc552._.js")
R.c("server/chunks/ssr/_339f24bb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__68d47023._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bc499f6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c5ca667._.js")
R.m(34736)
module.exports=R.m(34736).exports
