module.exports=[70406,(e,t,r)=>{t.exports=e.x("next/dist/compiled/@opentelemetry/api",()=>require("next/dist/compiled/@opentelemetry/api"))},42849,(e,t,r)=>{t.exports=e.x("airtable-9fd4456b18d345df",()=>require("airtable-9fd4456b18d345df"))},14142,e=>e.a(async(t,r)=>{try{let t=await e.y("resend-8394417a8534d297");e.n(t),r()}catch(e){r(e)}},!0),34147,e=>e.a(async(t,r)=>{try{var a=e.i(42849),s=e.i(14142),n=t([s]);[s]=n.then?(await n)():n;let o=new a.default({apiKey:process.env.AIRTABLE_API_KEY}).base(process.env.AIRTABLE_BASE_ID),l=new s.Resend(process.env.RESEND_API_KEY);async function i(e,t){if("POST"!==e.method)return t.status(405).json({message:"Method Not Allowed"});try{let{uid:r,email:a,name:s,photoUrl:n,provider:i,role:d}=e.body;if(!r||!a)return t.status(400).json({message:"Missing required fields"});let u=o("Users"),c=await u.select({filterByFormula:`{firebase_uid} = '${r}'`,maxRecords:1}).firstPage(),p=!1,f="";if(c.length>0){f=c[0].id;let e=c[0].fields.role;return t.status(200).json({success:!0,recordId:f,isNewUser:p,dbRole:e})}{p=!0,f=(await u.create([{fields:{firebase_uid:r,email:a,name:s||a.split("@")[0],provider:i||"unknown",role:d||"patient",...n?{photo_url:n}:{}}}]))[0].id;let e=process.env.ADMIN_EMAIL,t=process.env.RESEND_FROM_EMAIL||"onboarding@resend.dev";if(e&&process.env.RESEND_API_KEY)try{await l.emails.send({from:`ConnectingDocs <${t}>`,to:e,subject:`🎉 새 유저 가입 알림: ${s||a}`,html:`
                            <div style="font-family: sans-serif; p-line-height: 1.5;">
                                <h2>새로운 유저가 가입했습니다!</h2>
                                <ul>
                                    <li><strong>이름:</strong> ${s||"미입력"}</li>
                                    <li><strong>이메일:</strong> ${a}</li>
                                    <li><strong>권한(Role):</strong> ${d||"patient"}</li>
                                    <li><strong>가입 방식:</strong> ${i}</li>
                                </ul>
                                <p>Airtable의 Users 테이블에서 확인하실 수 있습니다.</p>
                            </div>
                        `}),console.log(`Admin notification sent to ${e} for new user ${a}`)}catch(e){console.error("Failed to send admin notification email:",e)}}return t.status(200).json({success:!0,recordId:f,isNewUser:p})}catch(e){return console.error("Error syncing user to Airtable:",e),t.status(500).json({message:"Internal Server Error",error:e.message})}}e.s(["default",()=>i]),r()}catch(e){r(e)}},!1),66880,e=>e.a(async(t,r)=>{try{var a=e.i(26747),s=e.i(90406),n=e.i(44898),i=e.i(62950),o=e.i(34147),l=e.i(7031),d=e.i(81927),u=e.i(46432),c=t([o]);[o]=c.then?(await c)():c;let f=(0,i.hoist)(o,"default"),h=(0,i.hoist)(o,"config"),g=new n.PagesAPIRouteModule({definition:{kind:s.RouteKind.PAGES_API,page:"/api/auth/sync",pathname:"/api/auth/sync",bundlePath:"",filename:""},userland:o,distDir:".next",relativeProjectDir:""});async function p(e,t,r){g.isDev&&(0,u.addRequestMeta)(e,"devRequestTimingInternalsEnd",process.hrtime.bigint());let s="/api/auth/sync";s=s.replace(/\/index$/,"")||"/";let n=await g.prepare(e,t,{srcPage:s});if(!n){t.statusCode=400,t.end("Bad Request"),null==r.waitUntil||r.waitUntil.call(r,Promise.resolve());return}let{query:i,params:o,prerenderManifest:c,routerServerContext:p}=n;try{let r=e.method||"GET",a=(0,l.getTracer)(),n=a.getActiveScopeSpan(),u=g.instrumentationOnRequestError.bind(g),f=async n=>g.render(e,t,{query:{...i,...o},params:o,allowedRevalidateHeaderKeys:[],multiZoneDraftMode:!1,trustHostHeader:!1,previewProps:c.preview,propagateError:!1,dev:g.isDev,page:"/api/auth/sync",internalRevalidate:null==p?void 0:p.revalidate,onError:(...t)=>u(e,...t)}).finally(()=>{if(!n)return;n.setAttributes({"http.status_code":t.statusCode,"next.rsc":!1});let e=a.getRootSpanAttributes();if(!e)return;if(e.get("next.span_type")!==d.BaseServerSpan.handleRequest)return void console.warn(`Unexpected root span type '${e.get("next.span_type")}'. Please report this Next.js issue https://github.com/vercel/next.js`);let i=e.get("next.route");if(i){let e=`${r} ${i}`;n.setAttributes({"next.route":i,"http.route":i,"next.span_name":e}),n.updateName(e)}else n.updateName(`${r} ${s}`)});n?await f(n):await a.withPropagatedContext(e.headers,()=>a.trace(d.BaseServerSpan.handleRequest,{spanName:`${r} ${s}`,kind:l.SpanKind.SERVER,attributes:{"http.method":r,"http.target":e.url}},f))}catch(e){if(g.isDev)throw e;(0,a.sendError)(t,500,"Internal Server Error")}finally{null==r.waitUntil||r.waitUntil.call(r,Promise.resolve())}}e.s(["config",0,h,"default",0,f,"handler",()=>p]),r()}catch(e){r(e)}},!1)];

//# sourceMappingURL=%5Broot-of-the-server%5D__8c412ca0._.js.map