import Head from 'next/head';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { useState } from 'react';
import { LanguageCode } from '@/utils/translations';

export default function TermsOfService() {
  const [currentLang, setCurrentLang] = useState<LanguageCode>('EN');

  return (
    <div className="bg-[#050505] min-h-screen text-slate-50 font-sans">
      <Head>
        <title>Terms of Service | Connecting Docs</title>
        <meta name="description" content="Connecting Docs Terms of Service — the rules and guidelines for using our platform." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href="https://connectingdocs.ai/terms" />
      </Head>

      <Header currentLang={currentLang} onLangChange={setCurrentLang} />

      <main className="max-w-3xl mx-auto px-6 py-28">
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-sm text-slate-500 mb-10">
          <Link href="/" className="hover:text-cyan-400 transition-colors">Home</Link>
          <span>/</span>
          <span className="text-slate-300">Terms of Service</span>
        </div>

        <div className="mb-12">
          <span className="inline-block px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-mono tracking-widest uppercase mb-4">
            Legal
          </span>
          <h1 className="text-4xl font-bold text-white mb-3">Terms of Service</h1>
          <p className="text-slate-500 text-sm">Last updated: February 2026</p>
        </div>

        {/* Important Disclaimer */}
        <div className="mb-10 p-5 rounded-2xl border border-amber-500/30 bg-amber-500/5">
          <div className="flex items-start gap-3">
            <span className="text-xl mt-0.5">⚠️</span>
            <div>
              <p className="text-amber-300 font-semibold mb-1">Medical Disclaimer</p>
              <p className="text-amber-200/70 text-sm leading-relaxed">
                Connecting Docs provides <strong>educational information only</strong>. Our AI-generated reports are not medical advice, diagnosis, or treatment recommendations. Always consult a licensed medical professional before making any decisions about your health or aesthetic treatments.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-8">

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-400 leading-relaxed">
              By accessing or using Connecting Docs (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service. These Terms apply to all visitors, users, and account holders.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p className="text-slate-400 leading-relaxed">
              Connecting Docs is an AI-powered platform that analyzes user-submitted health and skin-related survey data to generate personalized educational reports about aesthetic treatment options. The platform is available in English, Korean, Japanese, and Chinese.
            </p>
            <p className="text-slate-400 leading-relaxed mt-3">
              The Service is intended for <strong className="text-white">informational and educational purposes only</strong> and does not constitute medical advice. Reports generated by the platform are not a substitute for professional medical consultation.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">3. User Accounts</h2>
            <div className="space-y-3 text-slate-400 leading-relaxed">
              <p>To access full features (including saved reports), you must create an account. You are responsible for:</p>
              <ul className="space-y-2">
                {[
                  'Providing accurate and complete registration information',
                  'Maintaining the confidentiality of your login credentials',
                  'All activities that occur under your account',
                  'Notifying us immediately of any unauthorized use',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-2 w-1.5 h-1.5 rounded-full bg-cyan-400 flex-shrink-0" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p>You must be at least 18 years old to create an account. Accounts are non-transferable.</p>
            </div>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="text-slate-400 leading-relaxed mb-3">You agree not to:</p>
            <ul className="space-y-2 text-slate-400">
              {[
                'Use the Service for any unlawful purpose',
                'Submit false, misleading, or fraudulent survey data',
                'Attempt to reverse engineer, scrape, or copy the AI recommendation engine',
                'Share your account with others or create multiple accounts',
                'Use the Service to harass, harm, or impersonate any person',
                'Interfere with or disrupt the integrity or performance of the Service',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-red-400/70 flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">5. AI-Generated Content & Limitations</h2>
            <p className="text-slate-400 leading-relaxed">
              Reports are generated by an AI system trained on clinical protocol data. While we strive for accuracy, AI-generated content may contain errors or may not reflect the most current medical research. The Service:
            </p>
            <ul className="mt-3 space-y-2 text-slate-400">
              {[
                'Does NOT replace consultation with a licensed medical professional',
                'Does NOT diagnose any medical condition',
                'Does NOT guarantee treatment outcomes',
                'May reflect clinical data that is not yet updated to the latest standards',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-amber-400/70 flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p className="text-slate-400 leading-relaxed">
              All content, design, code, and data on the Connecting Docs platform is the exclusive property of Connecting Docs and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without express written permission.
            </p>
            <p className="text-slate-400 leading-relaxed mt-3">
              Your personalized report is licensed to you for personal, non-commercial use only.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">7. Pricing & Payments</h2>
            <p className="text-slate-400 leading-relaxed">
              Basic analysis reports are available for free with a registered account. Premium features may require payment. All pricing is displayed clearly before purchase. We reserve the right to modify pricing with advance notice. Payments are non-refundable unless required by applicable law.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p className="text-slate-400 leading-relaxed">
              To the fullest extent permitted by law, Connecting Docs shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service. Our total liability shall not exceed the amount paid by you to us in the 12 months preceding the claim.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">9. Termination</h2>
            <p className="text-slate-400 leading-relaxed">
              We reserve the right to suspend or terminate your account at our discretion if you violate these Terms. You may delete your account at any time by contacting us. Upon termination, your access to saved reports will cease, but we will provide a 30-day window to export your data upon request.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">10. Governing Law</h2>
            <p className="text-slate-400 leading-relaxed">
              These Terms are governed by applicable laws. Any disputes shall be resolved through good-faith negotiation first, and then through binding arbitration if unresolved. Nothing in these Terms waives statutory consumer protection rights available in your jurisdiction.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
            <h2 className="text-xl font-semibold text-white mb-3">11. Changes to Terms</h2>
            <p className="text-slate-400 leading-relaxed">
              We may update these Terms from time to time. We will notify registered users by email before material changes take effect. Continued use of the Service after the effective date constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section className="p-6 rounded-2xl border border-cyan-500/10 bg-cyan-500/5">
            <h2 className="text-xl font-semibold text-white mb-3">12. Contact</h2>
            <p className="text-slate-400 leading-relaxed">For questions about these Terms, contact us at:</p>
            <div className="mt-3 space-y-1 text-slate-300">
              <p><strong className="text-white">Connecting Docs</strong></p>
              <p>Email: <a href="mailto:hello@connectingdocs.ai" className="text-cyan-400 hover:underline">hello@connectingdocs.ai</a></p>
              <p>Website: <a href="https://connectingdocs.ai" className="text-cyan-400 hover:underline">connectingdocs.ai</a></p>
            </div>
          </section>

        </div>
      </main>

      <Footer language={currentLang} />
    </div>
  );
}
