var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/pages/doctor/patient/[id].js")
R.c("server/chunks/ssr/_3e01abb3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84687bd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_pages_58755233.js")
R.c("server/chunks/ssr/[externals]__dd7cc552._.js")
R.c("server/chunks/ssr/_339f24bb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__68d47023._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bc499f6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c5ca667._.js")
R.m(81129)
module.exports=R.m(81129).exports
