var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/pages/login.js")
R.c("server/chunks/ssr/_7978b9d1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84687bd7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f4fd2a3a._.js")
R.c("server/chunks/ssr/[externals]__dd7cc552._.js")
R.c("server/chunks/ssr/_339f24bb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__68d47023._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bc499f6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c5ca667._.js")
R.m(50674)
module.exports=R.m(50674).exports
