module.exports=[70406,(e,t,r)=>{t.exports=e.x("next/dist/compiled/@opentelemetry/api",()=>require("next/dist/compiled/@opentelemetry/api"))},14142,e=>e.a(async(t,r)=>{try{let t=await e.y("resend-8394417a8534d297");e.n(t),r()}catch(e){r(e)}},!0),89057,e=>e.a(async(t,r)=>{try{var n=e.i(14142),s=t([n]);[n]=s.then?(await s)():s;let o=new n.Resend(process.env.RESEND_API_KEY),i=process.env.RESEND_FROM_EMAIL||"onboarding@resend.dev",l=process.env.ADMIN_EMAIL||"";async function a(e,t){if("POST"!==e.method)return t.status(405).json({error:"Method not allowed"});let{to:r,subject:n,html:s,type:a,data:d}=e.body;if(!r)return t.status(400).json({error:"Missing recipient"});if(!process.env.RESEND_API_KEY)return console.warn("[EMAIL] RESEND_API_KEY not set. Logging email instead:"),console.log(`To: ${r}
Subject: ${n}`),t.status(200).json({success:!0,id:"no_key_mock_"+Date.now()});try{let e=[];if(r&&s&&e.push(o.emails.send({from:i,to:[r],subject:n||"[Connecting Docs] Your Personal Skin Analysis Report",html:s})),l&&d){let t=`
                <h2>🔔 새 설문 완료 알림</h2>
                <p><strong>사용자 이메일:</strong> ${d.userEmail||r}</p>
                <p><strong>주요 목표:</strong> ${d.primaryGoal||"-"}</p>
                <p><strong>피부 타입:</strong> ${d.skinType||"-"}</p>
                <p><strong>Top 추천:</strong> ${d.topProtocol||"-"}</p>
                ${d.reportId?`<p><strong>리포트 링크:</strong> <a href="http://localhost:3001/report/${d.reportId}">/report/${d.reportId}</a></p>`:""}
                <hr/>
                <p style="color:#666;font-size:12px">Connecting Docs 자동 알림</p>
            `;e.push(o.emails.send({from:i,to:[l],subject:`[Connecting Docs] 새 환자 설문 완료 - ${d.userEmail||"비회원"}`,html:t}))}let a=await Promise.all(e);return console.log("[EMAIL] Sent successfully:",a.map(e=>e.data?.id)),t.status(200).json({success:!0,ids:a.map(e=>e.data?.id)})}catch(e){return console.error("[EMAIL] Send failed:",e),t.status(500).json({error:e.message||"Failed to send email"})}}e.s(["default",()=>a]),r()}catch(e){r(e)}},!1),19015,e=>e.a(async(t,r)=>{try{var n=e.i(26747),s=e.i(90406),a=e.i(44898),o=e.i(62950),i=e.i(89057),l=e.i(7031),d=e.i(81927),p=e.i(46432),u=t([i]);[i]=u.then?(await u)():u;let m=(0,o.hoist)(i,"default"),g=(0,o.hoist)(i,"config"),h=new a.PagesAPIRouteModule({definition:{kind:s.RouteKind.PAGES_API,page:"/api/email/send",pathname:"/api/email/send",bundlePath:"",filename:""},userland:i,distDir:"/sessions/tender-eager-darwin/.next-build",relativeProjectDir:""});async function c(e,t,r){h.isDev&&(0,p.addRequestMeta)(e,"devRequestTimingInternalsEnd",process.hrtime.bigint());let s="/api/email/send";s=s.replace(/\/index$/,"")||"/";let a=await h.prepare(e,t,{srcPage:s});if(!a){t.statusCode=400,t.end("Bad Request"),null==r.waitUntil||r.waitUntil.call(r,Promise.resolve());return}let{query:o,params:i,prerenderManifest:u,routerServerContext:c}=a;try{let r=e.method||"GET",n=(0,l.getTracer)(),a=n.getActiveScopeSpan(),p=h.instrumentationOnRequestError.bind(h),m=async a=>h.render(e,t,{query:{...o,...i},params:i,allowedRevalidateHeaderKeys:[],multiZoneDraftMode:!1,trustHostHeader:!1,previewProps:u.preview,propagateError:!1,dev:h.isDev,page:"/api/email/send",internalRevalidate:null==c?void 0:c.revalidate,onError:(...t)=>p(e,...t)}).finally(()=>{if(!a)return;a.setAttributes({"http.status_code":t.statusCode,"next.rsc":!1});let e=n.getRootSpanAttributes();if(!e)return;if(e.get("next.span_type")!==d.BaseServerSpan.handleRequest)return void console.warn(`Unexpected root span type '${e.get("next.span_type")}'. Please report this Next.js issue https://github.com/vercel/next.js`);let o=e.get("next.route");if(o){let e=`${r} ${o}`;a.setAttributes({"next.route":o,"http.route":o,"next.span_name":e}),a.updateName(e)}else a.updateName(`${r} ${s}`)});a?await m(a):await n.withPropagatedContext(e.headers,()=>n.trace(d.BaseServerSpan.handleRequest,{spanName:`${r} ${s}`,kind:l.SpanKind.SERVER,attributes:{"http.method":r,"http.target":e.url}},m))}catch(e){if(h.isDev)throw e;(0,n.sendError)(t,500,"Internal Server Error")}finally{null==r.waitUntil||r.waitUntil.call(r,Promise.resolve())}}e.s(["config",0,g,"default",0,m,"handler",()=>c]),r()}catch(e){r(e)}},!1)];

//# sourceMappingURL=%5Broot-of-the-server%5D__be6a250d._.js.map